apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: user-portal
build:
  artifacts:
    - image: harbor.cyverse.org/de/portal2
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/portal2.yml
