apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  templates:
  - name: atmosphere-grant-access
    steps:
    - - name: ldap-add-user-to-atmosphere-group
        template: ldap-add-user-to-group
        arguments:
          parameters:
          - name: group
            value: "atmo-user"
          - name: uid
            value: "{{workflow.parameters.user_id}}"
    - - name: atmosphere-api-grant-access-request
        template: api-grant-access-request
        arguments:
          parameters:
          - name: service_name
            value: "atmosphere"
    - - name: atmosphere-email-access-granted
        template: email-access-granted
        arguments:
          parameters:
          - name: service_name
            value: "Atmosphere"
          - name: service_url
            value: "{{workflow.parameters.portal_api_base_url}}/services/atmosphere"
          - name: email_address
            value: "{{workflow.parameters.email}}"
    - - name: atmosphere-api-subscribe-mailing-list
        template: api-subscribe-mailing-list
        arguments:
          parameters:
          - name: list_name
            value: "atmosphere-users"
          - name: email
            value: "{{workflow.parameters.email}}"

  - name: bisque-grant-access
    steps:
    - - name: bisque-create-user
        template: bisque-create-user
        arguments:
          parameters:
          - name: user_id
            value: "{{workflow.parameters.user_id}}"
          - name: email
            value: "{{workflow.parameters.email}}"
    - - name: bisque-create-irods-directory
        template: create-service-directory
        arguments:
          parameters:
          - name: user_id
            value: "{{workflow.parameters.user_id}}"
          - name: path
            value: "bisque_data"
    - - name: bisque-api-grant-access-request
        template: api-grant-access-request
        arguments:
          parameters:
          - name: service_name
            value: "bisque"
    - - name: bisque-email-access-granted
        template: email-access-granted
        arguments:
          parameters:
          - name: service_name
            value: "BisQue"
          - name: service_url
            value: "{{workflow.parameters.portal_api_base_url}}/services/bisque"
          - name: email_address
            value: "{{workflow.parameters.email}}"
    - - name: bisque-api-subscribe-mailing-list
        template: api-subscribe-mailing-list
        arguments:
          parameters:
          - name: list_name
            value: "bisque-users"
          - name: email
            value: "{{workflow.parameters.email}}"

  - name: coge-grant-access
    steps:
    - - name: coge-create-irods-directory
        template: create-service-directory
        arguments:
          parameters:
          - name: user_id
            value: "{{workflow.parameters.user_id}}"
          - name: path
            value: "coge_data"
    - - name: coge-email-access-granted
        template: email-access-granted
        arguments:
          parameters:
          - name: service_name
            value: "CoGe"
          - name: service_url
            value: "{{workflow.parameters.portal_api_base_url}}/services/coge"
          - name: email_address
            value: "{{workflow.parameters.email}}"
    - - name: coge-api-grant-access-request
        template: api-grant-access-request
        arguments:
          parameters:
          - name: service_name
            value: "coge"

  - name: data-commons-grant-access
    steps:
    - - name: data-commons-api-grant-access-request
        template: api-grant-access-request
        arguments:
          parameters:
          - name: service_name
            value: "datacommons"
    - - name: data-commons-email-access-granted
        template: email-access-granted
        arguments:
          parameters:
          - name: service_name
            value: "Data Commons"
          - name: service_url
            value: "{{workflow.parameters.portal_api_base_url}}/services/data-commons"
          - name: email_address
            value: "{{workflow.parameters.email}}"

  - name: discovery-environment-grant-access
    steps:
    - - name: de-ldap-add-user-to-group
        template: ldap-add-user-to-group
        arguments:
          parameters:
          - name: group
            value: "de-preview-access"
          - name: uid
            value: "{{workflow.parameters.user_id}}"
    - - name: discovery-environment-api-grant-access-request
        template: api-grant-access-request
        arguments:
          parameters:
          - name: service_name
            value: "discoveryenvironment"
    - - name: de-email-access-granted
        template: email-access-granted
        arguments:
          parameters:
          - name: service_name
            value: "Discovery Environments"
          - name: service_url
            value: "{{workflow.parameters.portal_api_base_url}}/services/atmosphere"
          - name: email_address
            value: "{{workflow.parameters.email}}"
    - - name: discovery-environment-subscribe-mailing-list-de
        template: api-subscribe-mailing-list
        arguments:
          parameters:
          - name: list_name
            value: "de-users"
          - name: email
            value: "{{workflow.parameters.email}}"
    - - name: discovery-environment-subscribe-mailing-list-datastore
        template: api-subscribe-mailing-list
        arguments:
          parameters:
          - name: list_name
            value: "datastore-users"
          - name: email
            value: "{{workflow.parameters.email}}"

  - name: sciapps-grant-access
    steps:
    - - name: sciapps-create-irods-directory
        template: create-service-directory
        arguments:
          parameters:
          - name: user_id
            value: "{{workflow.parameters.user_id}}"
          - name: path
            value: "sci_data"
    - - name: sciapps-api-grant-access-request
        template: api-grant-access-request
        arguments:
          parameters:
          - name: service_name
            value: "sciapps"
    - - name: sciapps-email-access-granted
        template: email-access-granted
        arguments:
          parameters:
          - name: service_name
            value: "SciApps"
          - name: service_url
            value: "{{workflow.parameters.portal_api_base_url}}/services/sciapps"
          - name: email_address
            value: "{{workflow.parameters.email}}"
            
# Tasks
#######

  - name: create-service-directory
    inputs:
      parameters:
      - name: user_id
      - name: path
    steps:
    - - name: create-directory
        template: irods-mkdir
        arguments:
          parameters:
          - name: path
            value: "/iplant/home/{{inputs.parameters.user_id}}/{{inputs.parameters.path}}"
    - - name: set-inherit
        template: irods-chmod-inherit
        arguments:
          parameters:
          - name: path
            value: "/iplant/home/{{inputs.parameters.user_id}}/{{inputs.parameters.path}}"
    - - name: set-owner
        template: irods-chmod-own
        arguments:
          parameters:
          - name: user
            value: "{{inputs.parameters.user_id}}"
          - name: path
            value: "/iplant/home/{{inputs.parameters.user_id}}/{{inputs.parameters.path}}"

  - name: bisque-create-user
    inputs:
      parameters:
      - name: user_id
      - name: email
    container:
      image: localhost:5000/portal2
      env:
      - name: BISQUE_ENDPOINT
        value: "{{workflow.parameters.bisque_url}}"
      - name: BISQUE_USERNAME
        value: "{{workflow.parameters.bisque_username}}"
      - name: BISQUE_PASSWORD
        value: "{{workflow.parameters.bisque_password}}"
      command: [/usr/src/app/bisque_create_user.py]
      args: ["{{inputs.parameters.user_id}}", "{{inputs.parameters.email}}"]

  - name: irods-mkdir
    inputs:
      parameters:
      - name: path
    container:
      image: localhost:5000/portal2
      env:
      - name: IRODS_ENVIRONMENT_FILE
        value: "/usr/src/app/irods_environment.json"
      command: [imkdir]
      args: ["-p", "{{inputs.parameters.path}}"]

  - name: irods-chmod-inherit
    inputs:
      parameters:
      - name: path
    container:
      image: localhost:5000/portal2
      env:
      - name: IRODS_ENVIRONMENT_FILE
        value: "/usr/src/app/irods_environment.json"
      command: [ichmod]
      args: ["inherit", "{{inputs.parameters.path}}"]

  - name: irods-chmod-own
    inputs:
      parameters:
      - name: user
      - name: path
    container:
      image: localhost:5000/portal2
      env:
      - name: IRODS_ENVIRONMENT_FILE
        value: "/usr/src/app/irods_environment.json"
      command: [ichmod]
      args: ["own", "{{inputs.parameters.user}}", "{{inputs.parameters.path}}"]

  - name: email-access-granted
    inputs: 
      parameters:
      - name: service_name
      - name: service_url
      - name: email_address
    container:
      image: localhost:5000/portal2
      env:
      - name: SERVICE_NAME
        value: "{{inputs.parameters.service_name}}"
      - name: SERVICE_URL
        value: "{{inputs.parameters.service_url}}"
      - name: EMAIL_ADDRESS
        value: "{{inputs.parameters.email_address}}"
      command: [sh, -c]
      args: ["cat /usr/src/app/templates/access_granted.txt | envsubst | ssmtp -vvv {{inputs.parameters.email_address}}"]

  - name: ldap-add-user-to-group
    inputs:
      parameters:
      - name: group
      - name: uid
    container:
      image: localhost:5000/portal2
      command: [sh, -c]
      args: ['echo "dn: cn={{inputs.parameters.group}},ou=Groups,dc=iplantcollaborative,dc=org\nchangetype: modify\nadd: memberUid\nmemberUid: {{inputs.parameters.uid}}" | ldapmodify -H {{workflow.parameters.ldap_host}} -D {{workflow.parameters.ldap_admin}} -w {{workflow.parameters.ldap_password}}']

  - name: api-grant-access-request
    inputs:
      parameters:
      - name: service_name
    container:
      image: localhost:5000/portal2
      command: [curl]
      #TODO add api key or authorization header argument: "-H 'Authorization: foo'"
      args: ["-v", "-X POST", "-H", "Content-Type: application/json", "-d", "{ \"status\": \"granted\" }", "{{workflow.parameters.portal_api_base_url}}/services/{{inputs.parameters.service_name}}/requests"]

  - name: api-subscribe-mailing-list
    inputs:
      parameters:
      - name: list_name
      - name: email
    container:
      image: localhost:5000/portal2
      command: [curl]
      #TODO add authorization header argument: "-H 'Authorization: foo'"
      args: ["-v", "-X POST", "-H", "Content-Type: application/json", "-d '{ name: {{inputs.parameters.list_name}}, email: {{inputs.parameters.email}}, subscribe: true }'", "{{workflow.parameters.portal_api_base_url}}/mailing_lists/subscriptions/"]