apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-

# Workflows 
###########
spec:
  templates:
  - name: update-password
    steps:
    - - name: irods-set-user-password
        template: irods-set-user-password
        arguments:
          parameters:
          - name: user_id
            value: "{{workflow.parameters.user_id}}"
          - name: password
            value: "{{workflow.parameters.password}}"
    - - name: ldap-change-password
        template: ldap-change-password
        arguments:
          parameters:
          - name: uid
            value: "{{workflow.parameters.user_id}}"
          - name: password
            value: "{{workflow.parameters.password}}"
    - - name: ldap-update-shadow-last-change
        template: ldap-update-shadow-last-change
        arguments:
          parameters:
          - name: uid
            value: "{{workflow.parameters.user_id}}"

  - name: create-user
    steps:
    - - name: ldap-create-user
        template: ldap-create-user
        arguments:
          parameters:
          - name: first_name
            value: "{{workflow.parameters.first_name}}"
          - name: last_name
            value: "{{workflow.parameters.last_name}}"
          - name: email
            value: "{{workflow.parameters.email}}"
          - name: uid
            value: "{{workflow.parameters.user_id}}"
          - name: uidNumber
            value: "{{workflow.parameters.user_id_number}}"
          - name: password
            value: "{{workflow.parameters.password}}"
          - name: department
            value: "{{workflow.parameters.department}}"
          - name: organization
            value: "{{workflow.parameters.organization}}"
          - name: title
            value: "{{workflow.parameters.title}}"
    - - name: ldap-add-user-to-everyone-group
        template: ldap-add-user-to-group
        arguments:
          parameters:
          - name: group
            value: "iplant-everyone"
          - name: uid
            value: "{{workflow.parameters.user_id}}"
    - - name: ldap-add-user-to-community-group
        template: ldap-add-user-to-group
        arguments:
          parameters:
          - name: group
            value: "community"
          - name: uid
            value: "{{workflow.parameters.user_id}}"
    - - name: irods-create-user
        template: irods-create-user
        arguments:
          parameters:
          - name: user_id
            value: "{{workflow.parameters.user_id}}"
    - - name: irods-set-user-password
        template: irods-set-user-password
        arguments:
          parameters:
          - name: user_id
            value: "{{workflow.parameters.user_id}}"
          - name: password
            value: "{{workflow.parameters.password}}"
    - - name: irods-grant-ipcservices-access-to-user-directory
        template: irods-chmod-own
        arguments:
          parameters:
          - name: user
            value: "ipcservices"
          - name: path
            value: "/iplant/home/{{workflow.parameters.user_id}}"
    - - name: irods-grant-rodsamin-access-to-user-directory
        template: irods-chmod-own
        arguments:
          parameters:
          - name: user
            value: "rodsadmin"
          - name: path
            value: "/iplant/home/{{workflow.parameters.user_id}}"
    - - name: mailchimp-subscribe-user
        template: mailchimp-subscribe-user
        arguments:
          parameters:
          - name: email
            value: "{{workflow.parameters.email}}"
          - name: first_name
            value: "{{workflow.parameters.first_name}}"
          - name: last_name
            value: "{{workflow.parameters.last_name}}"

  - name: delete-user
    steps:
    - - name: ldap-delete-user
        template: ldap-delete-user
        arguments:
          parameters:
          - name: uid
            value: "{{workflow.parameters.user_id}}"
    - - name: irods-delete-user
        template: ldap-delete-user
        arguments:
          parameters:
          - name: uid
            value: "{{workflow.parameters.user_id}}"
    - - name: mailchimp-unsubscribe-user
        template: mailchimp-unsubscribe-user
        arguments:
          parameters:
          - name: email
            value: "{{workflow.parameters.email}}"

# Tasks
#######

  - name: irods-create-user
    inputs:
      parameters:
      - name: user_id
    container:
      image: localhost:5000/portal2
      command: [iadmin]
      args: ["mkuser", "{{inputs.parameters.user_id}}", "rodsuser"]

  - name: irods-delete-user
    inputs:
      parameters:
      - name: user_id
    container:
      image: localhost:5000/portal2
      command: [iadmin]
      args: ["rmuser", "{{inputs.parameters.user_id}}"]

  - name: irods-set-user-password
    inputs:
      parameters:
      - name: user_id
      - name: password
    container:
      image: localhost:5000/portal2
      command: [iadmin]
      args: ["moduser", "{{inputs.parameters.user_id}}", "password", "{{inputs.parameters.password}}"]

  - name: irods-chmod-own
    inputs:
      parameters:
      - name: user
      - name: path
    container:
      image: localhost:5000/portal2
      command: [ichmod]
      args: ["own", "{{inputs.parameters.user}}", "{{inputs.parameters.path}}"]

  #FIXME duplicated in services.yaml
  - name: ldap-add-user-to-group
    inputs:
      parameters:
      - name: group
      - name: uid
    container:
      image: localhost:5000/portal2
      command: [sh, -c]
      args: ['echo "dn: cn={{inputs.parameters.group}},ou=Groups,dc=iplantcollaborative,dc=org\nchangetype: modify\nadd: memberUid\nmemberUid: {{inputs.parameters.uid}}" | ldapmodify -H {{workflow.parameters.ldap_host}} -D {{workflow.parameters.ldap_admin}} -w {{workflow.parameters.ldap_password}}']
  
  - name: ldap-create-user
    inputs:
      parameters:
      - name: first_name
      - name: last_name
      - name: email
      - name: uid
      - name: uidNumber
      - name: password
      - name: department
      - name: organization
      - name: title
    container:
      image: localhost:5000/portal2
      command: [sh, -c]
      args: ['echo "dn: uid={{inputs.parameters.uid}},ou=People,dc=iplantcollaborative,dc=org\nobjectClass: posixAccount\nobjectClass: shadowAccount\nobjectClass: inetOrgPerson\ngivenName: {{inputs.parameters.first_name}}\nsn: {{inputs.parameters.last_name}}\ncn: {{inputs.parameters.first_name}} {{inputs.parameters.last_name}}\nuid: {{inputs.parameters.uid}}\nuserPassword: {{inputs.parameters.password}}\nmail: {{inputs.parameters.email}}\ndepartmentNumber: {{inputs.parameters.department}}\no: {{inputs.parameters.organization}}\ntitle: {{inputs.parameters.title}}\nhomeDirectory: /home/{{inputs.parameters.uid}}\nloginShell: /bin/bash\ngidNumber: 10013\nuidNumber: {{inputs.parameters.uidNumber}}\nshadowLastChange:{{workflow.parameters.daysSinceEpoch}}\nshadowMin: 1\nshadowMax: 730\nshadowInactive: 10\nshadowWarning: 10" | ldapadd -H {{workflow.parameters.ldap_host}} -D {{workflow.parameters.ldap_admin}} -w {{workflow.parameters.ldap_password}}']

  - name: ldap-change-password
    inputs:
      parameters:
        - name: uid
        - name: password
    container:
      image: localhost:5000/portal2
      command: [ldappasswd]
      args: [
        "-H", "{{workflow.parameters.ldap_host}}", 
        "-D", "uid={{inputs.parameters.uid}},ou=People,dc=iplantcollaborative,dc=org",
        "-w", "{{workflow.parameters.ldap_password}}",
        "-s", "{{inputs.parameters.password}}",
      ]

  - name: ldap-update-shadow-last-change
    inputs:
      parameters:
        - name: uid
    container:
      image: localhost:5000/portal2
      command: [sh, -c]
      args: ['echo "dn: uid={{inputs.parameters.uid}},ou=People,dc=iplantcollaborative,dc=org\nshadowLastChange:{{workflow.parameters.daysSinceEpoch}}" | ldapmodify -H {{workflow.parameters.ldap_host}} -D {{workflow.parameters.ldap_admin}} -w {{workflow.parameters.ldap_password}}']


  - name: ldap-delete-user
    inputs:
      parameters:
      - name: uid
    container:
      image: localhost:5000/portal2
      command: [sh, -c]
      args: ['echo "dn: uid={{inputs.parameters.uid}},ou=People,dc=iplantcollaborative,dc=org" | ldapdelete -H {{workflow.parameters.ldap_host}} -D {{workflow.parameters.ldap_admin}} -w {{workflow.parameters.ldap_password}}']

  - name: mailchimp-subscribe-user
    inputs:
      parameters:
      - name: first_name
      - name: last_name
      - name: email
    container:
      image: localhost:5000/portal2
      command: [curl]
      args: [
        "--verbose", 
        "--location",
        "--request", "POST", 
        "--header", "Authorization: Basic {{workflow.parameters.mailchimp_api_key}}", 
        "--header", "Content-Type: application/json",
        "--data", "{\"email_address\":\"{{inputs.parameters.email}}\",\"status\":\"subscribed\",\"merge_fields\":{\"FNAME\":\"{{input.parameters.first_name}}\",\"LNAME\":\"{{input.parameters.last_name}}\"}}",
        "{{workflow.parameters.mailchimp_api_url}}/lists/{{workflow.parameters.mailchimp_list_id}}/members",
      ]

  - name: mailchimp-unsubscribe-user
    inputs:
      parameters:
      - name: email
    container:
      image: localhost:5000/portal2
      command: [curl]
      args: [
        "--verbose", 
        "--location",
        "--request", "POST", 
        "--header", "Authorization: Basic {{workflow.parameters.mailchimp_api_key}}", 
        "--header", "Content-Type: application/json",
        "--data", "{\"email_address\":\"{{inputs.parameters.email}}\",\"status\":\"unsubscribed\"}",
        "{{workflow.parameters.mailchimp_api_url}}/lists/{{workflow.parameters.mailchimp_list_id}}/members",
      ]
